### ISSUE TITLE
Creating new chapters and chapter pages

### ISSUE THREAD

**Issue by mohad12211** [BKSalman/musawarah#31]

**Comment by mohad12211** [comment]
where can a user create chapters and pages for the comics?
first, where can a user find a list for his comics? we can add a route for the user's own comics, and have buttons to add a chapter/page?
PS: I don't know what does "page" mean in this context xD

**Comment by BKSalman** [comment]
> where can a user create chapters and pages for the comics?

can be like a small + button in the comic page ( just added it to #22 as a todo )

>  first, where can a user find a list for his comics? we can add a route for the user's own comics, and have buttons to add a chapter/page?

could add an issue for user profile that will display user info and list comics author by that user

>  PS: I don't know what does "page" mean in this context xD

the pages of a chapter hahaha

**Comment by mohad12211** [comment]
> could add an issue for user profile that will display user info and list comics author by that user

https://github.com/BKSalman/musawarah/blob/main/client/src/routes/%5Busername%5D/%2Bpage.svelte
the username route actually exist, but it looks outdated, might work on it.

**Comment by mohad12211** [comment]
closed for #22 and #32
