### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by mohad12211** [BKSalman/musawarah#32]
### Todos:
- [x] shows user info
- [x] shows user comics
- [ ] page design

**Comment by mohad12211** [comment]
will be at this route which seems outdated https://github.com/BKSalman/musawarah/blob/main/client/src/routes/%5Busername%5D/%2Bpage.svelte

**Comment by BKSalman** [comment]
this issue can be closed since the design stuff can be on a different issue instead
