### ISSUE TITLE
duplicate comic for each genre in get_comics

### ISSUE THREAD

**Issue by mohad12211** [BKSalman/musawarah#39]
The join
https://github.com/BKSalman/musawarah/blob/4482caa3e3269a640767cabb684c44d223b16931/src/comics/routes.rs#L250
in
https://github.com/BKSalman/musawarah/blob/4482caa3e3269a640767cabb684c44d223b16931/src/comics/routes.rs#L247-L253
is causing each comic to appear once for each genre it has.

**Comment by mohad12211** [comment]
so
```diff
diff --git a/src/comics/routes.rs b/src/comics/routes.rs
index f0609a8..22f2988 100644
--- a/src/comics/routes.rs
+++ b/src/comics/routes.rs
@@ -268,6 +268,7 @@ pub async fn get_comics(
     }
 
     let (comics, users): (Vec<Comic>, Vec<User>) = comics_query
+        .distinct()
         .limit(10)
         .select((Comic::as_select(), User::as_select()))
         .load::<(Comic, User)>(&mut db)
```
this looks like it solves it, and it doesn't seem to break querying genre, can you test/confirm?

**Comment by BKSalman** [comment]
yep, it works
