### ISSUE TITLE
Shorten links

### ISSUE THREAD

**Issue by mohad12211** [BKSalman/musawarah#50]
- [x] use comic title instead of comic_id
	- [x] have a way to encode the title properly to be a valid url. (certain titles be be invalid in this case, should be alright)
- [x] use chapter number instead of chapter_id
- [x] make (user_id, title) unique in the comics table, instead of (title) only
- [ ] limit title length
- [ ] adhere to REST conventions in the APIs that uses slugs

**Comment by BKSalman** [comment]
Also we can use comic title instead of id, since it's already unique

But for that we might need to somehow handle having spaces in the title

**Comment by mohad12211** [comment]
that's correct, I never thought about that, but it might be annoying, if it was unique for each user, it would've been good, but it being unique across all comics sounds annoying, maybe making the combination (userid, title) unique is better? so the route be:
username/comic_title/1 ?

**Comment by mohad12211** [comment]
an even better step is to have a very small id with the title to make duplicate titles possible, like what reddit does

**Comment by mohad12211** [comment]
for example, an id with 5 characters in base64 can give us 1,073,741,824 possible comics for each title for each user.

**Comment by BKSalman** [comment]
Very good ideas, I'm not sure which one is better tbh, but I kinda like the username + title one, because it's more share friendly, and for people who just wanna type the link directly

**Comment by mohad12211** [comment]
yes, I'm not a comic expert (lol) but I would doubt that a user would publish two comics under the same name.
similar to how a writer wouldn't publish two books with the same name.
so it's safe to just have username/comic_title/chapter_number imo, without even needing a small ID.
because chapter numbers seems more relevant and browserable than chapter titles.

**Comment by BKSalman** [comment]
:ok: ye
