### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by BKSalman** [BKSalman/musawarah#7]
### Todos:
- [x] form validation
- [ ] page design
- [x] migrate [superforms](https://superforms.rocks/migration) to 1.0

**Comment by mohad12211** [comment]
should we show the validation messages in Arabic as well?
relevant: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap

**Comment by BKSalman** [comment]
> should we show the validation messages in Arabic as well?
> 
> relevant: https://github.com/colinhacks/zod/blob/master/ERROR_HANDLING.md#customizing-errors-with-zoderrormap

Yes for sure, I thought we would do it all without localization, then add it to everything, but if it's better that way, then there is no harm doing it either way

**Comment by mohad12211** [comment]
I agree, the above method is better after we setup l10n.
